### ISSUE TITLE
UTC/Timezone issue

### ISSUE THREAD

**Issue by sikadiamond** [mtanda/grafana-heatmap-epoch-panel#10]
Dear,

I think there is an issue with the date/time on the heatmaps.

Please see the screenshot:
https://www.dropbox.com/s/83hbn4lp03h423k/Screenshot%202016-07-11%2014.38.20.png?dl=0

My dashboard is set to UTC, but the results of the heatmap are converted to my current Timezone.
The queries used to build the heatmap are the same as above. But only the heatmap shows a time shift of about 2 hours.

Please advise.

**Comment by mtanda** [comment]
Thanks for feedback!

It seems to be a bug. I'll check it later.

**Comment by sikadiamond** [comment]
Juist want to clarify things:

https://www.dropbox.com/s/rpairpisfchbdav/Screenshot%202016-07-14%2017.13.15.png?dl=0

The heatmap has difficulty respecting where the data stops & starts.

It seems to always stretch...

**Comment by mtanda** [comment]
I fix several bug of this panel, and request to register latest version.
https://github.com/grafana/grafana-plugin-repository/pull/31
I'm waiting for merging the PR, and available to user.

I'm not sure what cause your issue, but latest version might fix your issue (I think).
So, please wait for next release, or try latest version in GitHub.

instruction to use latest version in GitHub:

```
cd <somewhere>
git clone git@github.com:mtanda/grafana-heatmap-epoch-panel.git
sudo vim /etc/grafana/grafana.ini
# add following line
# [plugin.mtanda-heatmap-epoch-panel]
# path = <somewhrere>/grafana-heatmap-epoch-panel

sudo rm -rf /var/lib/grafana/plugins/mtanda-heatmap-epoch-panel/
sudo service grafana-server restart
```

**Comment by sikadiamond** [comment]
Dear, 

Lots of improvements!
Windowing etc is perfect now.
Only one problem the legend date is stil 2hrs off in my case. UTC of the dashboard is not respected.

Example here: https://www.dropbox.com/s/i485hhm0a7vowqv/Screenshot%202016-07-15%2011.59.13.png?dl=0

**Comment by mtanda** [comment]
Oh, thanks for testing!
I got it, UTC issue is remain.

I succeed to replicate your issue by setting timezone to UTC.
![utc](https://cloud.githubusercontent.com/assets/224552/16871867/4e4822b4-4ac4-11e6-9733-4dc863f435d3.png)

I'll fix it.

**Comment by mtanda** [comment]
I fix timezone issue in v0.1.5!

**Comment by sikadiamond** [comment]
Awsome!

Works perfect.

Would you ever implement the auto upper size feature?

If you clear the field now in the heatmap options pannel, it says auto, but does't scale.

So now I try a high value just to be sure there are no values out of the graph scope.

**Comment by mtanda** [comment]
@sikadiamond add it!
https://github.com/mtanda/grafana-heatmap-epoch-panel/pull/14
