### ISSUE TITLE
Can't load plugin on Grafana 3.1.0

### ISSUE THREAD

**Issue by cedr-x** [mtanda/grafana-heatmap-epoch-panel#16]
Hello,
I've this annoying issue when I select Add Panel > HeatmapEpoch

```
Plugin Error
Error loading http://localhost:3000/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js as "./heatmap" from http://localhost:3000/public/plugins/mtanda-heatmap-epoch-panel/module.js

```

I've no clues on this error. Tried both Grafana 3.0.4 and 3.1 , git clone and grafana-cli install ways, disabled selinux... I still have the same problem. 

btw, I'm using Influxdb, but I suppose there is no incidences at this stage

**Comment by mtanda** [comment]
Currently, grafana.net reject my plugin, can't install by grafana-cli.
Workaround is installing by "git clone", I do like this.

```
sudo git clone --depth 1 https://github.com/mtanda/grafana-heatmap-epoch-panel.git /var/lib/grafana/plugins/mtanda-heatmap-epoch-panel
```

It works for me.

If you already install plugin, remove it by following command.

```
/var/lib/grafana/plugins/mtanda-heatmap-epoch-panel
```

And then, try "git clone" again?

**Comment by cedr-x** [comment]
it did not work
what I did :
grafana-cli plugins uninstall mtanda-heatmap-epoch-panel
sudo rm -rf /var/lib/grafana/plugins/mtanda-heatmap-epoch-panel
sudo git clone --depth 1 https://github.com/mtanda/grafana-heatmap-epoch-panel.git /var/lib/grafana/plugins/mtanda-heatmap-epoch-panel
sudo service grafana-server restart

Still have the issue 
![capture d ecran de 2016-07-27 13-40-29](https://cloud.githubusercontent.com/assets/8896445/17174292/bb1de50a-5400-11e6-92f2-ef9effe064eb.png)

**Comment by mtanda** [comment]
hmm, did you try to clear browser cache?
What browser do you use?

**Comment by cedr-x** [comment]
Oh ! it's Seamonkey 2.40 (based on Gecko / Firefox 43). I've clean caches / sessions / also tried in private mode. 
But you've spotted the root cause : I don't have this issue with FF !
Thank you for your help

**Comment by mtanda** [comment]
Good for you :-)
