### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by flxai** [mtanda/grafana-heatmap-epoch-panel#17]
Hello,

I installed the plugin to my Grafana plugin directory. After restarting Grafana, the plugin seems to be recognized and I am able to add it via the interface to add new panels.

The problem is, when I try to do this, I get the following error:

> Plugin Error
> Error loading https://example.org/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js as "./heatmap" from https://example.org/public/plugins/mtanda-heatmap-epoch-panel/module.js

I replace my domain with `example.org`. The shown URL is visitable.

Is this a known bug? Is there a way to remedy this?

**Comment by mtanda** [comment]
What Grafana version do you use?
I use Grafana 3.1.0, and setup this plugin by following command.

```
sudo git clone --depth 1 https://github.com/mtanda/grafana-heatmap-epoch-panel.git /var/lib/grafana/plugins/mtanda-heatmap-epoch-panel
# after install restart grafana
```

It works.

**Comment by flxai** [comment]
I'm currently using Grafana 3.1.1.

I also have cloned the repo and use commit e1ec956. The location is:
`/var/lib/grafana-mysite/plugins/grafana-heatmap-epoch-panel`

**Comment by mtanda** [comment]
```
/var/lib/grafana-mysite/plugins/grafana-heatmap-epoch-panel
```

is not correct location.

```
/var/lib/grafana-mysite/plugins/mtanda-heatmap-epoch-panel
```

is correct location.

Please check my comment. https://github.com/mtanda/grafana-heatmap-epoch-panel/issues/17#issuecomment-239057647

**Comment by flxai** [comment]
Thank you. I tried your suggestions, but unfortunately it still does not work.

I also tried using the following path, of course also set up within grafana's config:
`/var/lib/grafana/plugins/mtanda-heatmap-epoch-panel`

This doesn't work either and the same error box pops up. In all cases, the script was loadable from the web server.

Is there some way I could debug this further?

**Comment by mtanda** [comment]
hmm, you can access plugin files by directly access the url?

**Comment by mtanda** [comment]
url like "https://example.org/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js".

**Comment by flxai** [comment]
Yes, accessing the URL does work.

**Comment by mtanda** [comment]
Sorry, late reply.
If the url is accessible, it should work.
Try to clear browser cache...

**Comment by pokemane** [comment]
@icks Do you have an ad blocker going?  Try disabling it on that page or that domain and remove the broken panel/row, clear cache/force refresh/etc and try re-adding the heatmap after that.

**Comment by flxai** [comment]
Thanks for your help and sorry for the wait.

@pokemane That's it! Disabling the ad blocker works for me. Never thought of that.

@mtanda Would it be possible to adapt the plugin to not be blocked by ad blockers?

**Comment by mtanda** [comment]
It is hard to resolve the issue in plugin side, please disabling ad blocker for Grafana page.

@pokemane Thanks for your help :-)

**Comment by alexanderzobnin** [comment]
Had the same issue in Grafana 4.x, but disabling ad blocker helps.
