### ISSUE TITLE
Browser hangs on low window size

### ISSUE THREAD

**Issue by flxai** [mtanda/grafana-heatmap-epoch-panel#18]
Hello again,

I'd like to use the plugin to use a low window size. Unfortunately, the browser hangs after reloading the dashboard containing the plugin.
#### Steps to reproduce
1. Create a new dashboard
2. Add a HeatmapEpoch panel
3. Add a random metric available to you
4. Change value of `Heatmap Options > Window Size` to **some value below 18**
5. Save the dashboard
6. Reload the dashboard
7. Browser should now hang

Is this a known bug? Are you able to reproduce this?

I tested this with the newest Firefox and Chromium.

**Comment by mtanda** [comment]
Sorry for late response.
I can't reproduce, I'll check if I get enough time.

**Comment by flxai** [comment]
Sorry to bug, but did you find some time yet?

**Comment by mtanda** [comment]
Today, I try it again. And success to replicate.
But, I don't have time to investigate the issue now.
To fix crash bug, it takes too much time.
Sorry, please wait.

**Comment by mtanda** [comment]
I can't replicate this on Chrome, it might be caused by Browser difference.

**Comment by mtanda** [comment]
hmm, ticks.time becomes 0. It should not be 0.
![image](https://cloud.githubusercontent.com/assets/224552/18616750/f845f5b0-7dfb-11e6-9980-789ff0b3d28f.png)

**Comment by mtanda** [comment]
https://github.com/mtanda/grafana-heatmap-epoch-panel/pull/21
This PR might fix your issue. Please check.

**Comment by flxai** [comment]
It works. Thanks!
