### ISSUE TITLE
Feature request: Geographic/location heatmap

### ISSUE THREAD

**Issue by RichiH** [mtanda/grafana-heatmap-epoch-panel#19]
Are there any plans to support geographic heatmaps as well? Think visualizations like
- https://pbs.twimg.com/media/BZ66wQtCMAAMCDj.jpg
- https://pbs.twimg.com/media/BZ65ZUUCAAIRc4L.jpg

In the generic case, this could also be very useful for things like visualizing heata distribution in a data center, requests in different clusters, etc.

**Comment by mtanda** [comment]
It is impossible to support such feature in this plugin...
The graph library what I use doesn't support geographic heatmaps.

Please try worldmap panel. (sorry, I don't test it with Prometheus datasource)
https://github.com/grafana/worldmap-panel

**Comment by RichiH** [comment]
Worldmap has several limitations which make it unsuitable; the worst of
them being that it uses differently-sized circles instead of an actual
heatmap.

If it's impossible to extend this plugin, feel free to close.

Thanks,
Richard

PS: Pity that you couldn't make it to promcon, I would have loved to meet
you in person.

**Comment by mtanda** [comment]
There is a feature request to support heatmap representation.
https://github.com/grafana/worldmap-panel/issues/17

I enjoy PromCon from Japan.
I'm very happy you think me as "loved to meet" :-)

**Comment by RichiH** [comment]
Yah, well, I would really like to talk to you if Cherry Dr. Pepper is as good as I imagine. ;) It's impossible to get in Germany :/

And of course talk about other stuff :)
