### ISSUE TITLE
How to make y-axis to instance index with influxdb

### ISSUE THREAD

**Issue by shane-zhang** [mtanda/grafana-heatmap-epoch-panel#20]
Hi, I am using this panel to display a time-series metrics data for multiple instances with influxdb, how to make the y-axis as the index of instance and the color as metrics.

**Comment by mtanda** [comment]
Sorry, I'm not sure what you want.
What is the metrics you want to display?

**Comment by shane-zhang** [comment]
Take the CPU usage of multiple PC as an example, I want to make y-axis as the index of the specific PC, and x-axis as time range, and the color's opacity as the usage of CPU.

**Comment by mtanda** [comment]
hmm, it is not supported, and it may be hard to add such feature...

**Comment by mtanda** [comment]
I'm not sure it is really called as "heatmap".
Anyway, the feature is out of scope, I close this.
