### ISSUE TITLE
Easy List blocking ajax request for heatmap.js

### ISSUE THREAD

**Issue by petemyron** [mtanda/grafana-heatmap-epoch-panel#22]
Trying to use the Heatmap panel on monitoringartist/Grafana-xxl 3.1.1 in docker on Ubuntu server. In Chrome (Version 53.0.2785.143 (64-bit)) on OSX with uBlock Origin 1.9.10 I see that the request for Heatmap.js?bust=whatever is blocked on EasyList for that specific filename, I suppose.

![image](https://cloud.githubusercontent.com/assets/627937/19668255/454d72cc-9a0b-11e6-9701-cdad0ee60793.png)

Though I think it's silly, consider changing the name or working with Easy List (but are there others?) to relax that setting. I imagine I'm not the only one that will get this blocked--I certainly can't deploy it if some of my users will also have it blocked.

**Comment by mtanda** [comment]
Ah..., I don't want to change the name. (The name follow common pattern in other panel plugin.)
The easylist contains many common file names, I think avoiding to use such name is not realistic.
https://easylist.to/easylist/easyprivacy.txt

I understand your situation, you are site admin or something, and deploy Grafana for other user.

Maybe, change file name (or append random suffix) in Grunt build process is better.

**Comment by mtanda** [comment]
According to https://github.com/grafana/grafana/issues/6649, this issue can be resolved by uBlock Origin setting.

I don't have a plan to fix this, so I close this issue.
