### ISSUE TITLE
Error while adding panel

### ISSUE THREAD

**Issue by red-led** [mtanda/grafana-heatmap-epoch-panel#26]
I have installed panel via grafana-cli and garfana shows this error when I'm trying to add HeatmapEpoch panel:

> Plugin Error
> (SystemJS) XHR error loading http://statserver/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js?bust=1493818738516
>     Error: XHR error loading http://statserver/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js?bust=1493818738516
>     Error loading http://statserver/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js as "./heatmap"
>              from http://statserver/public/plugins/mtanda-heatmap-epoch-panel/module.js

Tried to open this url, both are ok.

**Comment by mtanda** [comment]
If you use adblock plugin, please disable it, and try again.
It is known issue, and I don't fix it...

Next Grafana version will have great heatmap feature, so I'll stop this plugin development.
If you can upgrade your Grafana, please use Grafana official heatmap panel.

**Comment by red-led** [comment]
> If you use adblock plugin, please disable it, and try again.

Thanks, that works!
