### ISSUE TITLE
Panel won't load

### ISSUE THREAD

**Issue by johnseekins** [mtanda/grafana-heatmap-epoch-panel#7]
After installing the heatmap plugin, I get the following error when attempting to load it:

Error loading http://host:3000/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js as "./heatmap" from http://host:3000/public/plugins/mtanda-heatmap-epoch-panel/module.js

**Comment by mtanda** [comment]
Sorry, you might install this plugin by following README.
The REAME instruction is obsoleted, and I didn't update it...
Now, you can install this plugin by grafana-cli, it is correct way to install.

```
grafana-cli plugins install mtanda-heatmap-epoch-panel
```

Please try this.

**Comment by mtanda** [comment]
I can't replicate this if I install by grafana-cli, close this.

**Comment by exbane** [comment]
I receive the same error.. I tried both git cloning the repo into /var/lib/grafana/plugins and i've tried installing using grafana-cli (which only installed version 0.1.1).. 

Plugin Error
Error: XHR error loading http://grafana/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js?bust=1471024354527 Error loading http://grafana/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js as "./heatmap" from http://grafana/public/plugins/mtanda-heatmap-epoch-panel/module.js

right now i'm using the latest nightly build for Grafana from 8/11

**Comment by mtanda** [comment]
The plugin location is following path?

```
/var/lib/grafana/plugins/mtanda-heatmap-epoch-panel
```

Please check.
https://github.com/mtanda/grafana-heatmap-epoch-panel/issues/17#issuecomment-239057647

**Comment by pokemane** [comment]
Having the same issue; my path is also correct, and I've tried installing via direct clone (as in #17) and via grafana-cli.

![image](https://cloud.githubusercontent.com/assets/1995662/17740317/2c9ca03e-6466-11e6-92e3-ad3b1c02c3a5.png)

![image](https://cloud.githubusercontent.com/assets/1995662/17740325/3c5688aa-6466-11e6-8247-efa0e8f8fa9a.png)

custom.ini:

`plugins = C:\Metrics\grafana-3.1.0\data\plugins`

I've also tried clearing the browser cache multiple times.

## Edit:

Aha!  Ad blocker.  Wonderful.  It was blocking the XHR...  specifically, I'm using uBlock Origin.  Had to make an exception for my Grafana instance.  @mtanda , this is probably the issue in the other tickets for this problem as well, if I'd have to guess...

![image](https://cloud.githubusercontent.com/assets/1995662/17740580/24b29346-6467-11e6-9edc-30ecc3284adb.png)

## Edit 2:  Still having spotty success with the deactivation of the ad blocker.  I'll keep toying with it and report back... maybe someone else will have had some revelation in the meantime.

**Comment by mtanda** [comment]
@pokemane Thanks for your investigation!! It's great help for me!!
