### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by torkelo** [mtanda/grafana-heatmap-epoch-panel#8]
The readme is also used for grafana.net and for that you don't really need the clone instructions. But more importantly it would be great if you could also add more info in the readme about how this panel works, what data sources it supports etc. 

A changelog would also be good, mention that this panel is very early alpha state etc. The black y/x axis in the screenshot on grafana.net makes it looks like it's only a test and not ready for other to test so might be good to mention if this is readme

**Comment by mtanda** [comment]
I'm sorry. I should check carefully, and prepare instruction for user.
I'll update the README, and add CHANGELOG in this weekend.

**Comment by torkelo** [comment]
Awesome! Sorry, it was our mistake to publish it on grafana.net before it was ready :)

**Comment by mtanda** [comment]
@torkelo I update README.
The README becomes very brief...
Because I omit the explanation of Epoch library options, just refer the official document.
I add CHANGELOG.md too.

I worry about these are enough, would you check these documents?

**Comment by torkelo** [comment]
better, changelog could be in readme.md so it will show on Grafana.net
